[project]
name = "dag2diagram"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "croniter>=6.0.0",
    "dotenv>=0.9.9",
    "openai>=2.16.0",
    "ruff>=0.14.14",
    "tiktoken>=0.12.0",
]
